#
# Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

server:
  port: 8080
  host: 0.0.0.0

messaging-jms-demo:
  source: "jms"
  url: "jdbc:oracle:thin:@//129.146.63.193:1521/testpdb.auranet0.vcndns.oraclevcn.com"
  username: "aq#####"
  password: "AQ#####"
  queue: "demoqueue"
  config.numberofmessagestoconsume: -1
  channels:
    listenForMessagesWithPattern: "pattern regex..."
    subscribe: "pattern regex..."
    produce: "pattern regex..." # or sendMessagesWith...